### ISSUE TITLE
Error event vrapper in conjuction with jaspersoft Studio

### ISSUE THREAD

**Issue by KeesKuip** [vrapper/vrapper#727] opened 2016-02-25 12:23 UTC
The error below occurs very often in conjuction with the plugin of Jaspersoft Studio.
I do not know if this should be solved in vrapper and/or Jaspersoft Studio.

vrapper plugin:
  Vrapper	0.64.0	net.sourceforge.vrapper.feature.group	Vrapper Team

jaspersoft plugin (installed through eclipse marketplace):
  Jaspersoft Studio feature	6.2.0.final	com.jaspersoft.studio.feature.feature.group	TIBCO Software Inc.

net.sourceforge.vrapper.platform.VrapperPlatformException: Corrupt editor info structure found for editor com.jaspersoft.studio.editor.JrxmlEditor@656ab986
	at net.sourceforge.vrapper.eclipse.interceptor.EditorInfo.getChild(EditorInfo.java:62)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:286)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:352)
	at org.eclipse.ui.internal.PartService$6.run(PartService.java:149)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.PartService.partActivated(PartService.java:146)
	at org.eclipse.ui.internal.WorkbenchPage$17.run(WorkbenchPage.java:4870)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4867)
	at org.eclipse.ui.internal.WorkbenchPage.access$18(WorkbenchPage.java:4846)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:241)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:238)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:692)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:106)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.handleEvent(ContributedPartRenderer.java:61)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1453)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1416)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2855)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2425)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5236)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4680)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1097)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3322)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1041)
	at org.eclipse.gef.ui.parts.GraphicalEditor.setFocus(GraphicalEditor.java:428)
	at com.jaspersoft.studio.editor.part.MultiPageToolbarEditorPart.setFocus(MultiPageToolbarEditorPart.java:966)
	at com.jaspersoft.studio.editor.part.MultiPageToolbarEditorPart.setFocus(MultiPageToolbarEditorPart.java:949)
	at org.eclipse.ui.part.MultiPageEditorPart.setFocus(MultiPageEditorPart.java:1145)
	at org.eclipse.ui.part.MultiPageEditorPart.setFocus(MultiPageEditorPart.java:1127)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:191)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:253)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:225)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:107)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:795)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$2.setFocus(ContributedPartRenderer.java:100)
	at org.eclipse.swt.custom.CTabItem.setFocus(CTabItem.java:332)
	at org.eclipse.swt.custom.CTabFolder.setFocus(CTabFolder.java:2555)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:1052)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:3818)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3098)
	at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3055)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1259)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer$1.handleEvent(LazyStackRenderer.java:69)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:156)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4734)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:218)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:81)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:488)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:454)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:705)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1142)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3167)
	at org.eclipse.ui.internal.WorkbenchPage.access$23(WorkbenchPage.java:3125)
	at org.eclipse.ui.internal.WorkbenchPage$9.run(WorkbenchPage.java:3107)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3102)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3066)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3056)
	at org.eclipse.ui.internal.NavigationHistoryEntry.restoreLocation(NavigationHistoryEntry.java:66)
	at org.eclipse.ui.internal.NavigationHistory.gotoEntry(NavigationHistory.java:464)
	at org.eclipse.ui.internal.NavigationHistory.shiftEntry(NavigationHistory.java:529)
	at org.eclipse.ui.internal.NavigationHistory.backward(NavigationHistory.java:513)
	at org.eclipse.ui.internal.NavigationHistoryAction.run(NavigationHistoryAction.java:251)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:462)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by albertdev** [comment] 2016-02-25 13:29
I believe you are right in reporting this to us, it looks like Vrapper gets in some state where we didn't expect it to be.

I have recently made some fixes to Vrapper's editor handling so if you're impatient you could try upgrading to the newest unstable release.

If you don't have the opportunity to do that: what do you do with JasperStudio to get in this state? Can you reproduce it every time you create a project and create a new report or do you need to do some setup?

**Comment by KeesKuip** [comment] 2016-02-26 08:28
Hello Bert,
I’ve installed vrapper (0.65.20160215) unstable and it didn’t help.
I opened some reports and after opening I closed the editor.
I’ve attached the resulting errorlog.

When the ‘split editor plugin’ was installed I couldn’t edit a report at all. An assert was thrown.

Met vriendelijke groet,




Kees Kuip
MES Expert Center

[cid:image002.jpg@01D17077.D04DBDF0]

Cofely West Nederland BV
Albert Heijnweg 1, 1507 EH Zaandam | Postbus 104, 1500 EC Zaandam
+31 75 653 74 41 | kees.kuip@cofely-gdfsuez.nl

www.cofely-gdfsuez.nl<http://www.cofely-gdfsuez.nl> | ver vooruit in duurzame technologie

**Comment by albertdev** [comment] 2016-02-28 21:51
Ok, I was able to reproduce the problem.

It seems the Jasper Report editor says that it has 2 nested pages when it starts up but it will actually add the Preview tab half a second later. This will then surprise Vrapper which thinks its internal state got corrupted.

I guess I can let Vrapper deal with this, at worst we leak some memory when we keep a reference to tab pages which got removed. Closing the editor should reclaim that memory.

**Closed** 2016-02-28 22:22 UTC
Labels: Defect

**Comment by albertdev** [comment] 2016-02-28 22:24
The fix will be included in the next release and unstable build. Thanks for taking the time to report this issue.

**Comment by keforbes** [comment] 2016-03-01 01:58
I've updated the unstable update site with a new build (0.65.20160229) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!

**Comment by KeesKuip** [comment] 2016-03-01 10:02
Hello,

I gave the new build a try and it is looks as if my problem has been solved.
Thank you!

Best regards,
Kees Kuip
