### ISSUE TITLE
<F2> (Show Tooltip Description) causes cursor to disappear when working on i3wm

### ISSUE THREAD

**Issue by didiksupriadi41** [vrapper/vrapper#825] opened 2019-04-07 06:21 UTC
Pressing **F2** on a variable causes a pop-up to appears. Then when I hit **Escape** to get out of the pop-up, the cursor disappear.

**Comment by keforbes** [comment] 2019-04-09 20:13
I'm not able to reproduce this.  What OS are you using?  What version of Eclipse?  What type of file were you editing (java, c++, etc.)?

**Comment by didiksupriadi41** [comment] 2019-04-10 06:06
I was editing .java files with Eclipse 4.10 on Fedora 29.
but "maybe" it is also important to note that, I am using i3 window manager as my environment.

**Comment by albertdev** [comment] 2019-04-11 16:05
What was the expected behavior of the <kbd>F2</kbd> key? To which command did you assign this in Eclipse?

What happens when you disable Vrapper using the toggle button in the toolbar?

**Comment by didiksupriadi41** [comment] 2019-04-13 15:51
<kbd>F2</kbd> is assigned to Show Tooltip Description in Eclipse

**Comment by didiksupriadi41** [comment] 2019-04-13 16:08
Actually, when I tried this scenario on GNOME Desktop Environment, it works well. So, I think my issue is more specific on the i3 window manager.

**Comment by didiksupriadi41** [comment] 2019-04-20 17:35
I am sorry, I will close this issue because I found that this problem is not Vrapper responsibility to fix.

**Closed** 2019-04-20 17:35 UTC

**Comment by albertdev** [comment] 2019-04-25 14:30
No problem. Thanks for reporting back!

**Comment by JanSurft** [comment] 2020-10-01 06:43
@didiksupriadi41 did you find a solution? I'm facing the same problem, and it is very annoying, it also disappears after a hovering cursor tip. I'm also using the i3wm...

**Comment by goviedol** [comment] 2022-04-21 16:04
This is a problem with several years now, the lack of concern of Eclipse creator is horrible!. Many of us use Tiling Window Manager and we need to use Eclipse sometimes because is part of the daily job, and they do nothing about it!.
