### ISSUE TITLE
Indenting with >> in normal mode and with > in normal mode, seems to be broken

### ISSUE THREAD

**Issue by hawkprime** [vrapper/vrapper#687] opened 2015-09-21 23:26 UTC
With `tab` key inserting tab characters.

At any text line hit `>>` in normal mode and instead of indenting with one more tab it converts all tabs to 8 space characters and indents 8 more spaces in.

Same with visual mode, with single/multiple lines selected hit `>` and it changes everything to spaces as stated above.

Seems this was working back in version 36.

**Comment by albertdev** [comment] 2015-09-22 05:40
Did you recently upgrade, and to what version?
What kind of files are you editing? Do you have associated formatting rules in the Eclipse preferences?
Did you change your `.vrapperrc` file? If not, could you share it?

**Comment by hawkprime** [comment] 2015-09-22 16:58
I've been trying every few version after 36 just to check if the issue has been fixed but it seems that it is still not working right.

I am editing Java files. I downloaded a new clean version of Eclipse Java EE Mac 64x installed the Vrapper plugin and tried it out, it still exhibits the same behavior. I don't have a .vrapperrc file.

I've been able to reproduce this in Windows, Linux, and different Eclipse versions Kepler, Luna, Mars

**Comment by albertdev** [comment] 2015-09-22 17:07
Ah, it seems Vrapper 0.36.0 was the last version to use Eclipse's native indentation.

Version 0.38.0 and later includes code to do advanced indentation (e.g. indent 4 spaces, replace 8 spaces with tab if indenting again) and was configured through Vrapper options. You will likely have never customised your Vrapper install and hence it uses the default of spaces, 8 positions wide.

You might want to try the current unstable version because Vrapper finally gets its defaults from Eclipse, meaning that it should be less of a surprise to unsuspecting Vrapper users.

You could also wait for the next release (likely within 1 or 2 weeks), though it would help to see if the recent fixes help for your use case so that we can still tweak things if something would be wrong.

**Comment by hawkprime** [comment] 2015-09-22 18:04
Tried out 0.59 (unstable) and seems to be working as expected, thanks for looking into this.

**Comment by albertdev** [comment] 2015-09-22 19:27
Then I'm going to close this as a duplicate of #607. Feel free to comment on this issue if anything turns up.

**Closed by albertdev** 2015-09-22 19:27 UTC
