### ISSUE TITLE
Mouse cursor jumps when yank

### ISSUE THREAD

**Issue by umphy** [vrapper/vrapper#735] opened 2016-04-01 02:24 UTC
I have noticed that when I press `y` for yank, I can see a cusor flash at the start of the file even though the cursor itself doesn't seem to move.

The same flash occurs when I then press `Esc` to quit yank. Sometimes the flash is a bit too quick to see, so might have to try a few times.

**Comment by albertdev** [comment] 2016-04-01 07:30
I cannot reproduce this when using Mars 4.5.0 on Windows 10, jdk 1.6.0 45 (64 bit).

Does it always happen for any location or is it only when you e.g. moved the caret somewhere using the mouse?

Does this issue affect your workflow by jumping the file view up or down or is it merely a cosmetic problem?

**Comment by umphy** [comment] 2016-04-03 10:45
It actually doesn't jump the file view up or down, so it does not affect my workflow. I just happened to try and yank a line near the top of the file (with the first line in view) and noticed a flash at line 1 column 1.

I can see this happening on Windows 7, Mars 4.5.2. On a FreeBSD machine I can't see the flash, although I can't be sure if it's simply too fast or it's an OS related issue.

**Comment by albertdev** [comment] 2016-04-03 13:08
I'm going to mark this as an annoyance then, and even that might be too strongly worded. Please keep an eye on it (and your Eclipse log file) to see if there is something else going on.

Mainly the location of the caret when you're yanking (or the mode) can be important as closed folds may introduce funky behavior.

**Comment by umphy** [comment] 2016-04-05 00:51
I just upgraded to the latest stable version and can confirm the annoyance is still there.

I want to further clarify the issue. Originally I thought the cursor flash occured at line 1 col 1 of the file, but this is not correct. It flashes on the first line column 1 of the view. Have reproduced this in jsp, java and sql files.

**Comment by keforbes** [comment] 2018-02-13 16:26
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:26 UTC
Labels: Annoyance, Unconfirmed
