### ISSUE TITLE
<leader>q mapping starts recording a macro

### ISSUE THREAD

**Issue by mpkopec** [vrapper/vrapper#758] opened 2016-07-28 15:23 UTC
Hi!
First of all, thanks for great plugin! Unfortunately my mapping of `<leader>q` which executes `:q!` when used enters me to macro recording.

The background is that I have a few mappings to `<leader>` and `s` and `q` keys, e.g. `<leader>sq` saves and quits. Every one of this kind of mappings after pushing leader, then the next key is 'waiting' for another key. If I press `<leader>s` it waits, I push `space` and it saves, then changes the letter I'm on to space. If I press `<leader>q` it waits for another key, I push `space`, it closes the file and enters macro recording. My vrapperrc is generated by `grep` from my vimrc, which all can be found on github: [https://github.com/mpkopec/VimStuff](https://github.com/mpkopec/VimStuff).

This, I think, may be related to lack of timeout (issue #741), but that's only an idea.

**Comment by mpkopec** [comment] 2016-07-28 15:25
Fun fact, `<leader>h` and other like this to go between the tabs work correctly.

**Comment by albertdev** [comment] 2016-07-28 16:01
Thanks for your report and link to your `vrapperrc`!

The behaviour you see that `<leader>s` will indefinitely wait is explained by the lack of time-out, but pushing `<space>` should only trigger your `<leader>s` mapping and then the `<space>` motion which moves to the next char. Any other behaviour sounds like a bug.

This might be a duplicate of #756 though, which would mean the problem should be reproducible.

**Comment by mpkopec** [comment] 2016-07-28 16:38
Thanks for the reply, I will try to reproduce it and maybe provide more info on that.

See you around,
Maciek

**Comment by mpkopec** [comment] 2016-07-29 07:34
I have tested almost all the leader-based mappings from my vrapperrc, here what I got(as my `<leader>` is `,`, for simplicity I use `,` instead of the whole word `<leader>`):

- `,s` waits for another char, when `<cr>` hit it removes char under cursor and goes to new line leaving me in INSERT mode; it also prompts that pattern ',' was not found, it's like I would use `:s/,//`;
- `,q` waits for another char, when `<cr>` hit it simply quits; except having to hit `<cr>` it behaves normally,
- `,sq` does a combination of above; it behaves like `,s` (I can see the prompt text briefly before Vrapper leaves the buffer) and after hitting `<cr>` quits, of course after hitting `,sq` it waits for another char;
- `,qq` works as expected;
- `,sqq` works as expected;
- `,T` does not work at all, there is no command `:enew`;
- `,l`, `,h` work as expected;
- `,bl` works as expected;

To test it I used Xilinx SDK, which  is based on Eclipse 4.3.2, installed Vrapper version is 0.68.1

**Comment by albertdev** [comment] 2016-07-29 14:44
I can reproduce the behaviour you mention.

The problem is in all mappings which are a prefix of another mapping (`,s`, `,sq`, `,q`). Typing a "completion character" (you seem to prefer `<cr>`) to make the shorter mapping "stick" will trigger some edge case where the typed keys will be run again after the mapping.

It appears I introduced this bug in commit cf75ec2975a987c46f3c1732d0a3a399574f178c, though back then that change was for having access to the original input to stop endlessly recursive macros. It appears our testset didn't catch the breakage.

**Comment by albertdev** [comment] 2016-08-01 12:20
Small update: this bug will also cause a runaway insertion and StackOverflowError when you have something like the following commands and then press `,s<space>`:
```
:inoremap ,s start
:inoremap ,ss session
```

Please don't try this in your work environment. This means it **should** go out with the next release.

**Closed** 2016-08-01 20:04 UTC
Labels: Defect

**Comment by albertdev** [comment] 2016-08-01 20:14
I devised a fix which should be included in the next release and unstable build.

This should stop this bug from crashing Eclipse when using Insert mode or from doing seemingly random commands in Normal mode.

**Comment by mpkopec** [comment] 2016-08-01 20:15
Thank you! How and when can I test it, I mean download and integrate wrapper into my eclipse?

**Comment by albertdev** [comment] 2016-08-01 20:23
1. The name's Vrapper ;)
1. At certain times during the month @keforbes pushes a build to the "unstable" update site (basically the sneak-peak version), or you can wait for the bi-monthly release version which might in this case be available on the 7th of August (depending on whether we have the time to do so).

**Comment by mpkopec** [comment] 2016-08-01 20:26
Vrapper, ofc, typos occur xD Thanks for the info, I will sneak-peak in the next few days ;)

**Comment by keforbes** [comment] 2016-08-02 13:12
Hey, sorry, I'm on vacation all week so I won't be near my computer to do an unstable build.  Hopefully I can get to it this weekend, though I might just do a stable release instead since it's time.

**Comment by keforbes** [comment] 2016-08-07 19:49
Ok, sorry for the delay @mpkopec, I've released 0.70.0 with @albertdev's changes so go ahead and update and let us know if it fixes the problem.  Thanks!

**Comment by mpkopec** [comment] 2016-08-15 07:17
I have just tested simple file saving and it works well with any key as a trigger after `<leader>s` no weird actions are triggered. Thank you!
