### ISSUE TITLE
Word wrap (gq) doesn't respect tabstop

### ISSUE THREAD

**Issue by bjkail** [vrapper/vrapper#660] opened 2015-06-26 15:12 UTC
My team uses tabs rather than spaces, but comment lines are wrapped to 80 characters.  It appears gq counts tabs as a single character, which results in lines that are too long.

**Comment by albertdev** [comment] 2015-06-27 22:46
Indeed, I can reproduce this with Vrapper 0.56.

Marked as defect, I'll see what we can do about this.

**Comment by keforbes** [comment] 2015-06-27 23:12
I think the difficulty here is that we'll need to read the Eclipse settings to know how many spaces are being displayed for each tab character.  As of today I don't think there's any place where we read Eclipse settings for anything.

**Comment by bjkail** [comment] 2015-06-27 23:16
That would be ideal, but I would be content even if I could just set ts=4.

**Comment by albertdev** [comment] 2015-06-27 23:21
@keforbes 
I also thought of using `'tabstop'`, that seems to be okay for at least an initial implementation.

A while ago I was digging in the Eclipse API's to get the tab width in a generic way, it should be possible but it will be read-only to vrapper. It would be great for those users who didn't set the `tabstop` setting according to the principle of "least surprise". Maybe we need to make a seperate feature request to track it?

**Comment by kevinbisanz** [comment] 2015-08-13 03:40
I believe I have a fix for this issue that uses the 'tabstop' value.

Regarding Eclipse's tab width, it looks like Eclipse’s tab width can be retrieved via "EditorsUI.getPreferenceStore().getInt(AbstractDecoratedTextEditorPreferenceConstants.EDITOR_TAB_WIDTH)".  However in Options.java, the TAB_STOP value is defaulted to 8.  It is unclear to me how to tell when TAB_STOP has not been set explicitly and Vrapper should fall back to Eclipse’s value.

Any thoughts on how to tell when to use Vrapper's tabstop value vs. Eclipse's value?

**Comment by albertdev** [comment] 2015-08-13 10:03
@kevinbisanz 
For that I think we need some refactoring on the LocalConfiguration class, there needs to be some API to hook "default providers" into the DefaultEditorAdaptor and its configuration so that the current editor's tabsize can be checked.

Also, just reading the preferences is not enough. I noticed that the Java Formatter can override the general tab size, so I was thinking of hacking into the `getSourceViewerConfiguration()` method to get the effective tab size.

**Comment by kevinbisanz** [comment] 2015-08-14 02:08
@albertdev
Thanks for the info.  I'm going to be away from the computer for several days.  I'll look at your suggestions when I return.

**Comment by albertdev** [comment] 2015-08-14 02:55
@kevinbisanz
I'm more interested in your fix for this issue though, can I find it somewhere? I might deal with the tabstop thing this weekend.

**Closed** 2015-08-16 21:09 UTC
Labels: Defect

**Comment by albertdev** [comment] 2015-08-16 21:14
I fixed this issue and added some tests.

So far it is still reliant on a correct setting for `textwidth` and `tabstop`, reading that from Eclipse is left as extensions for #607.

**Comment by albertdev** [comment] 2015-08-20 08:49
@kevinbisanz I think I got the necessary changes to our Configuration API done and sitting in a local branch, I'll see how hard it is to grab the tab width.

**Comment by kevinbisanz** [comment] 2015-08-21 02:48
@albertdev Thanks for fixing this issue.  I pulled the changes you added and they work as expected with textwidth and tabstop set.
