### ISSUE TITLE
Failed to enter command mode

### ISSUE THREAD

**Issue by bennyty** [vrapper/vrapper#786] opened 2017-06-22 14:35 UTC
Vrapper on Windows 10, Eclipse Version: Neon.3 Release (4.6.3) Build id: 20170314-1500

Sometimes hitting `:` to enter command mode fails. I have to go back to the **barbaric** Ctrl-S to save! 😢 Restarting Eclipse has unreliably fixed this issue in the past.

```
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.ui
Error
Thu Jun 22 10:31:05 EDT 2017
Unhandled event loop exception

java.lang.RuntimeException: Failed to switch to mode net.sourceforge.vrapper.vim.modes.commandline.CommandLineMode@1a35343e
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:430)
	at net.sourceforge.vrapper.vim.commands.ChangeToCommandLineCommand.execute(ChangeToCommandLineCommand.java:30)
	at net.sourceforge.vrapper.vim.commands.CountAwareCommand.execute(CountAwareCommand.java:16)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.executeCommand(CommandBasedMode.java:264)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.handleKey(CommandBasedMode.java:318)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:831)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:467)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:442)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:291)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:485)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6044)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5733)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4918)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:364)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4799)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5110)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2552)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3822)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.TextLayout.setFont(TextLayout.java:2969)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:876)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:719)
	at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:216)
	at org.eclipse.swt.custom.StyledTextRenderer.getLineHeight(StyledTextRenderer.java:568)
	at org.eclipse.swt.custom.StyledText.getLinePixel(StyledText.java:4265)
	at org.eclipse.swt.custom.StyledText.handleTextChanging(StyledText.java:6361)
	at org.eclipse.swt.custom.StyledText$6.textChanging(StyledText.java:5707)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:76)
	at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:807)
	at org.eclipse.swt.custom.DefaultContent.replaceTextRange(DefaultContent.java:791)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7374)
	at org.eclipse.swt.custom.StyledText.replaceTextRange(StyledText.java:7984)
	at net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI.setPrompt(EclipseCommandLineUI.java:125)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandLineMode.enterMode(AbstractCommandLineMode.java:40)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:401)
	... 55 more
```

If it's relevant, my ~/.vrapperrc
```
"eclipseaction eclipsetogglecomment com.eclipse.ui.source.toggleComment
"nnoremap gcc :eclipsetogglecomment<cr>
"vnoremap gc  :eclipsetogglecomment<cr>

" show documentation for current symbol
eclipseuiaction eclipseshowdoc org.eclipse.ui.edit.text.showInformation
nnoremap K   :eclipseshowdoc<cr>

"show code-generation menu
eclipseaction eclipsesrcgenmenu org.eclipse.jdt.ui.edit.text.java.source.quickMenu
nnoremap crs        :eclipsesrcgenmenu<cr>
vnoremap <c-r><c-s> :eclipsesrcgenmenu<cr>gv

"show quickfix menu
eclipseuiaction eclipsequickfix org.eclipse.jdt.ui.edit.text.java.correction.assist.proposals
nnoremap <backspace> :eclipsequickfix<cr>
vnoremap <backspace> :eclipsequickfix<cr>

"show refactor menu
eclipseaction eclipserefactormenu org.eclipse.jdt.ui.edit.text.java.refactor.quickMenu
nnoremap crr        :eclipserefactormenu<cr>
vnoremap <c-r><c-r> :eclipserefactormenu<cr>gv

eclipseaction eclipsetogglebp org.eclipse.debug.ui.commands.ToggleBreakpoint
nnoremap <insert> :eclipsetogglebp<cr>

eclipseaction eclipseopenresource org.eclipse.ui.navigate.openResource
nnoremap <c-p> :eclipseopenresource<cr>

" amazing 'omnibox' that searches buffers, commands, views, menus, preferences, etc.
eclipseaction eclipsecmdsearch org.eclipse.ui.window.quickAccess
nnoremap <space> :eclipsecmdsearch<cr>
```

**Comment by keforbes** [comment] 2017-06-22 19:25
First of all, your `.vrapperrc` is amazing, good use of `eclipseaction`! 😄 


Anyway, I see in the stack trace that the error is:
```
java.lang.IllegalArgumentException: Argument not valid
```
which is from:
```
org.eclipse.swt.graphics.TextLayout.setFont
```
from vrapper's call:
```
net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI.setPrompt
```
The ecilpse docs say it could throw this error "if the font has been disposed".  It also says "a text style can override the default font".  Is it possible you're using some sort of custom font in your Eclipse?  Or custom styling?

**Comment by bennyty** [comment] 2017-06-22 19:36
I can't take any credit for my .vrapperrc, they are all stolen from [here](https://github.com/justinmk/config/blob/master/.vrapperrc)

I did suspect a font issue. I am using the Dark theme with [these settings.](http://imgur.com/JEd8aKn) All "default" settings.

**Comment by keforbes** [comment] 2017-06-22 20:41
This may be a strange question, but does the problem go away if you go back to the default light theme?

**Comment by bennyty** [comment] 2017-06-22 21:31
Not a strange question at all. It's hard to test though because the issue only happens sporadically. To anyone else reading this, try the dark theme, see if you encounter the same issue. I'll report back.

**Comment by keforbes** [comment] 2017-06-30 20:56
Did you ever find a way to resolve this issue?

**Comment by bennyty** [comment] 2017-07-06 14:43
@keforbes So heres my report after 2 weeks of testing. I spent a little a week with the standard white theme; no problems. Then I switched back to the dark theme; no problems... until today. It's entirely possible that I just didnt get lucky during the first week of testing.

Why would the font be disposed of?

**Comment by albertdev** [comment] 2017-08-15 16:51
I've been toying around with the dark theme for a bit but so far no crashes on Neon.1.

The command line "borrows" its parent editor's font. I could see it getting disposed if you change your preferences or if the parent editor was somehow hosted in a multi-page editor where those pages gets created and destroyed on the fly.

What kinds of projects do you have in Eclipse: Java, Android, Python, .... ?

**Comment by bennyty** [comment] 2017-08-15 17:10
It was a pure java project. I'm no longer on that project (successfully deployed :D) so if this is unconfirmed from everyone else I'll chalk it up to buggy work laptops.

**Comment by keforbes** [comment] 2018-02-13 16:27
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:27 UTC
Labels: Unconfirmed
