### ISSUE TITLE
Not working in Domino Designer (Eclipse Equinox 3.4ish)

### ISSUE THREAD

**Issue by lpar** [vrapper/vrapper#708] opened 2015-12-14 16:44 UTC
Toggle Vrapper shows up in the edit menu, but does nothing. Vrapper toolbar icon _doesn't_ show up.

Eclipse configuration details:
https://gist.github.com/lpar/4b2bb1f89736285422c8

I can't help noticing this in the Configuration Details dump:

    /instance/net.sourceforge.vrapper.eclipse/vrapperEnabled=false

It last worked a few months ago. I've installed a Domino fix pack since then, but no major update.

**Comment by keforbes** [comment] 2015-12-15 04:07
Eclipse 3.4?  Like, from 2008?  While I can't think of any feature we introduced that would be specific to a newer version, Eclipse themselves stopped support for 3.4 awhile ago.  Maybe you could try installing an older version of Vrapper?  I hate to say that since I don't know how far back you'd need to go but all of our previous versions are still available on sourceforge: http://sourceforge.net/projects/vrapper/files/vrapper/

**Comment by albertdev** [comment] 2015-12-15 08:55
@keforbes 
That's just the version of Equinox, the main JAR in the OSGi framework which Eclipse runs on.

This is one of the properties in that file:

> eclipse.buildId=20131002-1404

Likely the Eclipse version is thus newer, as one of the plugins from that installation has this version:

> org.eclipse.swt (3.7.2.v3740f-RCP20150506-1514)

I thus think IBM based their software on Eclipse Indigo (3.7) with some hotfixes merged in.

The only special thing I can see in this installation is that it uses IBM's J9 JVM as Java 1.6 runtime.

**Comment by lpar** [comment] 2016-01-04 18:37
OK, back from vacation, I've verified that 0.60.0 *does* work, and 0.62.0 does not. So it's something that changed in the latest release. What can I do to help narrow things down further?

**Comment by albertdev** [comment] 2016-01-04 21:14
Oh boy, I messed up. I managed to find my stash of old Eclipse versions (they got lost quite a while ago when reinstalling Windows 10), then tried version 0.62.0 in Eclipse 3.7 to be greeted with this upon starting:

![no-such-method-setalwaysshowscrollbar](https://cloud.githubusercontent.com/assets/1451362/12100389/e8ef836c-b32e-11e5-9a9c-d2c2840287bb.PNG)

The logfile then contained this piece of stacktrace:

````
!ENTRY org.eclipse.ui.workbench 4 2 2016-01-04 21:38:10.743
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.swt.custom.StyledText.setAlwaysShowScrollBars(Z)V
	at net.sourceforge.vrapper.eclipse.ui.CommandLineUIFactory.<init>(CommandLineUIFactory.java:39)
	at net.sourceforge.vrapper.eclipse.platform.EclipseUserInterfaceService.<init>(EclipseUserInterfaceService.java:41)
	at net.sourceforge.vrapper.eclipse.platform.EclipsePlatform.<init>(EclipsePlatform.java:85)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory.createInterceptor(VimInputInterceptorFactory.java:205)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptAbstractTextEditor(InputInterceptorManager.java:193)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptWorkbenchPart(InputInterceptorManager.java:134)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partOpened(InputInterceptorManager.java:382)
	at org.eclipse.ui.internal.PartListenerList2$5.run(PartListenerList2.java:130)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
````

Note that this window apparently only shows under a few lucky conditions. Trying to toggle Vrapper afterwards will never give that window, it only prints to the log.

As for the error itself, it's simply a case where I called a method which only got introduced in Eclipse 3.8 and hence does not exist in 3.7 or 3.6, see commit cda5e8832847f2e738a9ca45d37b0c9718d32c08. Seeing how that bit of code is not performance-critical, I might work around it using Java reflection. I must not have tested ever since with any old version...

Sorry for the trouble (and the delay in getting this reproduced), and thanks for posting your Eclipse details.

**Closed** 2016-01-04 23:10 UTC
Labels: Defect

**Comment by albertdev** [comment] 2016-01-04 23:13
Ok, that should have done the trick... Sorry once more!

**Comment by lpar** [comment] 2016-01-04 23:55
No problem, thanks for all the hard work on the project. It's a real sanity saver.

**Comment by keforbes** [comment] 2016-01-05 00:32
I've updated the unstable update site with a new build (0.63.20160104) which includes this fix.  Please give it a try and let us know how it goes.  Thanks!

**Comment by lpar** [comment] 2016-01-05 17:33
Yes, unstable update site version works. Thanks again.
