### ISSUE TITLE
Vrapper silently resets keybindings on install

### ISSUE THREAD

**Issue by karottenreibe** [vrapper/vrapper#361] opened 2014-01-22 14:02 UTC
I just installed Vrapper 0.38 from the stable update site and after restarting Eclipse during the install process, my custom keybindings are all (I think) reset. E.g. I defined a keybinding for the "Run as Java Application" action of "F11 J", which was reset to the Eclipse default value of "Ctrl+Alt+X J" after the Vrapper installation.

I would prefer if Vrapper did not change such unrelated keybindings or, if absolutely necessary, would at least ask me and let me save my current config somewhere before overwriting them.

**Comment by keforbes** [comment] 2018-02-13 16:25
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:25 UTC
Labels: Unconfirmed
