### ISSUE TITLE
Ctrl+O doesn't work with with some jumps

### ISSUE THREAD

**Issue by pa0los** [vrapper/vrapper#634] opened 2015-04-27 08:05 UTC
I noticed that CTRL+O (jump to previous location) doesn't behave the same way as in VIM. It doesn't go back when some jumps were made in the same file:
- jumps between marks ('<mark>)
- jump to end of file (G)
- jump to search location (/ or ?)

etc.
This should work according to:
http://vimdoc.sourceforge.net/htmldoc/motion.html#jump-motions
You can use '' (2x tick) instead but this only takes you one step back.

**Comment by albertdev** [comment] 2015-04-27 09:03
I believe this is a duplicate of issue #487 (well, unless we would suddenly choose to implement our own navigation history).

`Ctrl+O` actually does the same as clicking "Back" on the Eclipse toolbar, and you get different results compared to `''` since Vrapper doesn't push its jumps to Eclipse.

**Comment by pa0los** [comment] 2015-04-27 10:16
You are right, it's a duplicate - I must have missed it.

**Closed** 2015-04-27 21:05 UTC
