### ISSUE TITLE
Bug in block indentation with eclipse oxygen when only one character is selected

### ISSUE THREAD

**Issue by christianguenter2** [vrapper/vrapper#793] opened 2017-09-20 07:48 UTC
With eclipse neon I can do the following block indentation (ctrl + v, >) without problems. Note that only one character is selected.
![neon](https://user-images.githubusercontent.com/17437789/30632373-232255f0-9de8-11e7-9a7d-bfc751ccaef0.gif)

But with eclipse oxygen after the indentation the selected character is replaced with a >.
![oxygen](https://user-images.githubusercontent.com/17437789/30632490-9321deca-9de8-11e7-8d02-52096244f4c3.gif)

When multiple characters or multiple lines are selected it works as expected. 

![oxygen3](https://user-images.githubusercontent.com/17437789/30632531-b95424fe-9de8-11e7-8a11-e9a644ba2bb5.gif)

![oxygen4](https://user-images.githubusercontent.com/17437789/30632639-1b6fe89e-9de9-11e7-890b-291aaf103f5f.gif)

**Comment by christianguenter2** [comment] 2017-09-20 09:33
I did some more testing and it seems that the error only occurs with this remapping
vnoremap > >gv

**Comment by christianguenter2** [comment] 2017-09-20 09:58
hm, seems like another remapping in my configuration is causing the issue. Without my .vrapperrc I and solely with the above mentioned remappings I cannot reproduce the error. I have to check further.

**Comment by christianguenter2** [comment] 2017-09-22 08:40
I finally reduced my .vrapperrc file to the necessary mappings to reproduce the issue with eclipse oxygen

`vnoremap > >gv`
`nnoremap v- v$`
`nnoremap v <C-V>`
`nnoremap <C-V> v`

![oxygenx](https://user-images.githubusercontent.com/17437789/30736231-36e9fd5e-9f82-11e7-806e-82392d855d85.gif)

As said the mappings work with eclipse neon.

**Comment by christianguenter2** [comment] 2017-09-22 08:53
This workaround solves the issue for me
`nnoremap v> <C-V>>gv`

**Comment by albertdev** [comment] 2017-09-29 10:58
Thank you very much for your detailed report and these nice gifs!

Not only can I reproduce the problem with your

**Comment by albertdev** [comment] 2017-10-11 15:04
@christianguenter2 Apparently the exception with the stacktrace I posted above has been present since version 0.66.0 (released in March 2016). It depends on a mapping being triggered right after a non-matching mapping. Pressing any other keys before triggering the second mapping will work like you demonstrated because those extra keys reset Vrapper's internal state.

Then for some reason Eclipse Oxygen makes things weird because it will now insert the last-pressed character when Vrapper throws an exception. That is most definately new, but at least it indicates something is going wrong.

This should be fixed in the next release.

**Closed** 2017-10-11 15:07 UTC
Labels: Defect
