### ISSUE TITLE
Command-V to paste to the extended command line on Mac

### ISSUE THREAD

**Issue by McBrainy** [vrapper/vrapper#679] opened 2015-08-04 00:18 UTC
Okay, so this one's pretty minor, but it should also be pretty easy to fix. On a Mac, when I type ':' to enter an extended command, then Command-V to paste something to the command line, it instead pastes it to the editor. If I try Control-V, it works fine. But I expect to be able to paste with Command-V on a Mac. Based on [this article](http://alvinalexander.com/blog/post/jfc-swing/how-program-apple-command-key-keystroke-java-swing-mac-osx), it looks like you should be doing using `Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()` instead of `KeyEvent.CTRL_DOWN_MASK`.

**Comment by keforbes** [comment] 2015-08-04 02:05
I think we actually went out of our way to map the mac command key to the ctrl key due to a different user request.  The current workaround is to unbind `shift+insert` from Eclipse.  Eclipse binds both `Ctrl-V` and `shift-insert` to Paste so you can unbind whichever one you use less to be the command-line paste and continue using your favorite binding for pasting in the editor.  It isn't ideal, I know.  The problem is that we can't hijack any keys Eclipse is already using and pasting in the command-line is our own custom feature.

**Comment by keforbes** [comment] 2015-08-04 02:06
Heh, I should've read your description closer.  You already have a workaround of `Ctrl-V` since Eclipse on mac doesn't bind that to Paste.

**Comment by McBrainy** [comment] 2015-08-04 03:01
Eclipse came this way for me, with Command-V doing a paste, Command-S saving, etc. I did worry that you wouldn't be able to do the mapping. I don't see the shift-insert binding for paste in preferences, just Command-V.

**Comment by albertdev** [comment] 2015-10-27 09:25
We received a duplicate of #174 today and when searching for it I came across this issue.

Did you actually try unmapping `Command-V` from Eclipse's Keys preferences page? You might not be aware of it, but Vrapper never sees the `Command-V` shortcut when it's already bound to JDT's Paste action.

As far as I can see, Vrapper treats `Command` the same as `Control`.

**Comment by McBrainy** [comment] 2015-10-28 03:43
I unmapped Command-V and it works as expected now. The only oddity is that Command-V in normal mode starts visual block mode instead of pasting. By contrast, Command-V in normal mode in MacVim pastes.

**Comment by albertdev** [comment] 2015-11-02 16:35
I forgot to mention that you would see that behaviour by unmapping `Command-V`. Vrapper receives it and treats it like `Control-V` which is used for visual block mode.

You could add the following to your `.vrapperrc` if you want to use `Command-V` to paste in normal and insert mode, sadly that does mean that `Control-V` will also paste rather than entering block mode.

```
eclipseaction copy org.eclipse.ui.edit.copy
map <C-c> :copy<CR> 
```

**Comment by keforbes** [comment] 2016-04-04 20:37
I'm closing this issue.  Everything is working as expected and I think we've described all the necessary workarounds.  This comes down to our known limitation that all Eclipse bindings are checked before any key is passed to Vrapper and Vrapper has it's own definition for those keys when we see them.

**Closed by keforbes** 2016-04-04 20:37 UTC

**Comment by McBrainy** [comment] 2016-04-05 02:16
Actually, the issue I still see here is the fact that Vrapper treats Command-V like Control-V when Command-V has been unmapped. It makes the workaround less feasible and would be easy to fix.

**Comment by albertdev** [comment] 2016-04-05 09:08
@McBrainy
Originally Command became treated as if it were Control as a stop-gap solution for issue #465.

I think I could make it a unique modifier for remaps (I think it's `<D-x>` on MacVim), though I wonder if there are people who came to rely on Command == Control.

**Comment by keforbes** [comment] 2016-04-05 19:10
It looks like the `<D-x>` syntax isn't just specific to MacVim anymore, it was added into vim.
`:help key-notation`
```
<D-...>		command-key (Macintosh only)
```

We should probably add support for `<D-...>` syntax, though I don't know if we'd want to fallback to `<C-...>` for existing commands.  Like @albertdev said, there may be users expecting this behavior.  

I'm tempted to say we should introduce a setting for `TreatCmdLikeCtrl` but Vim doesn't have this setting; it simply ignores the command key.  I have an apple laptop running linux and if I hit `Command+c` Vim just treats it as the `c` character, which is basically the behavior observed in #465.  In that issue, the user was hitting `Command+s` and Vrapper was interpreting it as just `s`.  I guess that was actually the vim-compliant behavior. :confused:

**Comment by McBrainy** [comment] 2016-04-05 20:38
I don't know about a MacBook running Linux, but the usual way to get a Vim GUI on Mac is MacVim, which by default treats Command-C as copy, Command-V as paste, etc.

**Comment by albertdev** [comment] 2016-04-05 20:54
@keforbes 
Running Linux on an Apple laptop isn't the same as running MacVim - the keyboard will likely send the "Super" / "Windows" key when pressing Command ([if it sees it at all](http://vim.1045645.n5.nabble.com/Mapping-the-Super-Windows-key-td1175508.html)).

I've been thinking some more and realized that people likely didn't rely on Command to be mapped to Control - Eclipse or Mac OS X would rather steal the keypresses and MacVim only binds a few specific things to it.

I'm going to see if I can add the `<D-x>` prefix and then stop treating it as control. Once I got that, mapping `<D-v>` to paste should actually be possible as well - cut and copy should work as they are.

**Comment by albertdev** [comment] 2016-04-11 12:16
Ok, it should be supported now.

I thought that since we were going to the trouble of adding a new (unique) modifier I might as well bind a few of the MacVim shortcuts in Vrapper itself for a better out-of-the-box experience. `<D-c>` / `<D-x>` / `<D-v>` now actually call Eclipse operations in normal, visual and insert mode. In command line mode they're reassigned to server as copy / cut / paste for the command line selection.

If you want more commands you should also be able to use remappings by means of the `D-` prefix, though I guess you have to make sure that it doesn't conflict with a Mac OS X shortcut or Eclipse / Vrapper won't be able to receive the keypress event.

**Comment by keforbes** [comment] 2016-04-15 04:15
I've updated the unstable update site with a new build (0.67.20160414) which includes this fix.  If you get a chance, please try it out and let us know if it works for you.  Thanks!
