### ISSUE TITLE
UI frozon (infinite loop) in vrapper version 0.62 while refactoring "Extract local variable"

### ISSUE THREAD

**Issue by cebbec** [vrapper/vrapper#717] opened 2016-01-19 16:03 UTC
With a fresh eclipse installation (Version: Mars.1 Release (4.5.1) Build id: 20150924-1200) and the latest vrapper version 0.62, I have an intermittent bug while refactoring java code with "Extract Local Variable...". The refactoring dialog box open as usual but after clicking OK the dialog and the eclipse UI is stuck on an infinite loop (consume 1 core, I have to kill eclipse). I had this bug after upgrading Vrapper version from 0.60 to 0.62. I had a hard time finding the plugin responsible for this. I came back to the 0.60 version. Here is the stacktrace of the main UI thread while lock in the infinite loop :

```
"main" #1 prio=6 os_prio=0 tid=0x0000000002bff000 nid=0x2694 runnable [0x000000000012b000]
   java.lang.Thread.State: RUNNABLE
  at org.eclipse.swt.internal.win32.OS.SetScrollInfo(Native Method)
  at org.eclipse.swt.widgets.ScrollBar.SetScrollInfo(ScrollBar.java:770)
  at org.eclipse.swt.widgets.ScrollBar.setMaximum(ScrollBar.java:691)
  at org.eclipse.swt.custom.StyledText.setScrollBar(StyledText.java:9470)
  at org.eclipse.swt.custom.StyledText.setScrollBars(StyledText.java:9499)
  at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:7956)
  at org.eclipse.swt.custom.StyledText.redraw(StyledText.java:7513)
  at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.setCaret(EclipseCursorAndSelection.java:495)
  at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection$VisualCaretPainter.paintControl(EclipseCursorAndSelection.java:580)
  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
  at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1512)
  at org.eclipse.swt.widgets.Control.windowProc(Control.java:4733)
  at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
  at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
  at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
  at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3767)
  at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:172)
  at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:387)
  at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.run(RefactoringWizardDialog2.java:331)
  at org.eclipse.ltk.ui.refactoring.RefactoringWizard.internalPerformFinish(RefactoringWizard.java:637)
  at org.eclipse.ltk.ui.refactoring.UserInputWizardPage.performFinish(UserInputWizardPage.java:153)
  at org.eclipse.ltk.ui.refactoring.RefactoringWizard.performFinish(RefactoringWizard.java:710)
  at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog2.okPressed(RefactoringWizardDialog2.java:455)
  at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:466)
  at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
  at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
  at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
  at org.eclipse.jface.window.Window.open(Window.java:803)
  at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation$1.run(RefactoringWizardOpenOperation.java:187)
  at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
  at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:202)
  at org.eclipse.ltk.ui.refactoring.RefactoringWizardOpenOperation.run(RefactoringWizardOpenOperation.java:122)
  at org.eclipse.jdt.internal.ui.refactoring.actions.RefactoringStarter.activate(RefactoringStarter.java:38)
  at org.eclipse.jdt.ui.actions.ExtractTempAction.run(ExtractTempAction.java:88)
  at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:279)
  at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:251)
  at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
  at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:122)
  at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
  at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
  at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
  at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493)
  at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486)
  at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:286)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:507)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:558)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:378)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:324)
  at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:86)
  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1266)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1112)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
  at org.eclipse.swt.widgets.Control.traverse(Control.java:4163)
  at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4005)
  at org.eclipse.swt.widgets.Composite.translateMnemonic(Composite.java:1226)
  at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4023)
  at org.eclipse.swt.widgets.Display.translateMnemonic(Display.java:4850)
  at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1284)
  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3765)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
  at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
  at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
  at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
  at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
  at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
  at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
  at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.lang.reflect.Method.invoke(Unknown Source)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

   Locked ownable synchronizers:
  - None
```

**Comment by albertdev** [comment] 2016-01-19 16:22
Thank you for reporting this problem (I took the liberty of reformatting your post to get a better view of that stacktrace).

I can't say I've seen such a freeze before but the stacktrace does give a hint that it could be stuck in a redraw loop. We'll have to reproduce this. Seems you have the Windows version which I means I should be able to do it on my current development machine.

**Comment by albertdev** [comment] 2016-01-20 09:42
Woah, I had it happen immediately when I made a selection using "Extend selection" a few times (`Alt+Up` with default keybinds), right-clicked that selection and chose `Refactor > Extract Local Variable`. Vrapper will indeed make Eclipse burn up a sizeable chunk of processing power once you get to this state because it's in a redraw loop.

Sorry for making you lose your work, I'll have a look at this as soon as possible.

**Comment by albertdev** [comment] 2016-01-21 22:40
OK, the problem should be gone now, the fix will be in the next release and unstable builds.

Once more sorry for any hair loss or other afflictions.

**Closed** 2016-01-22 09:24 UTC
Labels: Defect

**Comment by keforbes** [comment] 2016-01-23 20:49
I've updated the unstable update site with a new build (0.63.20160123) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!
