### ISSUE TITLE
Assertion error on code complete

### ISSUE THREAD

**Issue by mladenuzelac** [vrapper/vrapper#641] opened 2015-05-25 15:31 UTC
Hi,

when I do code complete I get an assertion error.
1. I get code completion on a method (insert mode)
2. A list of suggested values pop up
3. I try to insert something assertion error pops up (vrapper is now in normal mode)
   Insertion is done via keyboard input

That error arises when operations on Map with HashMap implementations,
on normal methods, that error does not occur.

PS. If I select a value from the suggestion list, everything is fine.
      And Vrapper stays in insertion mode.

I did Java development in Eclipse Luna SR2, Vrapper is stable.
The same error happens on unstable version.

If I turn Vrapper off then the Eclipse behaviour is normal.
So when I get the drop down list and I press a key, my list gets narrower.
(Only values that starts with a pressed key are presented, I don't get an assertion error)

**Comment by albertdev** [comment] 2015-05-26 08:40
I think I have seen one of these before but I could not reproduce it...

Can you check your Eclipse error log and see if there are any Vrapper-related errors in there? You can do so by opening the "Error log" view and then clicking the small "Open Log" button at the top right of that little view.

**Comment by mladenuzelac** [comment] 2015-05-26 09:04
It says it's org.eclipse.jface error, it doesn't happen with vrapper disabled

here is the repository of the project. I marked points with TODO with short descriptions how to reproduce an error:
https://github.com/mladenuzelac/VrapperAssertBug

**Comment by albertdev** [comment] 2015-10-13 08:28
Thanks for going to the effort of making a testing project. I'm afraid however that I still couldn't reproduce the problem. I tried it again with Eclipse Mars and Vrapper 0.60.0 but also couldn't reproduce it.

Can you list what settings you changed in your `.vrapperrc`?

I'm marking this as "Unconfirmed" for now so that this doesn't get completely buried.

**Comment by mladenuzelac** [comment] 2015-10-13 11:26
I didn't do anything with .vrapperrc

I have tried now the project and everthing works fine with Mars 4.5.1 and
vrapper 0.6.0

**Comment by albertdev** [comment] 2015-11-10 08:44
@mladenuzelac 
Thanks for the update.
I haven't heard anything since your last update so I'm going to close this issue. Please reopen it if the same problem would reoccur.

**Closed by albertdev** 2015-11-10 08:44 UTC
Labels: Unconfirmed
