### ISSUE TITLE
VIM icon does not show up after installing vrapper 

### ISSUE THREAD

**Issue by finleyr** [vrapper/vrapper#695] opened 2015-10-29 23:36 UTC
Installed latest vrapper 0.60.0 onton eclipse IDE 1.5.2.20130211-1820  . No problem in the installation. Did reboot as directed.  However can not get VIM icon to appear on tool bar.
Any ideas?

**Comment by albertdev** [comment] 2015-11-02 16:37
Have you seen issue #690 where somebody had trouble installing Vrapper from the marketplace? What have you tried in the meantime?

Also, are you really sure that you Eclipse version is 1.5.2? That doesn't sound like any recent versioning scheme...

**Comment by finleyr** [comment] 2015-11-02 18:57
Thanks for responding. No, I had not seen issue #690, but I have just finished reading it and it is identical to my situation.  I have tried installing and reinstalling several times with different approaches.  I have tried the marketplace and I have tried pointing at the update site.   I have tried copying plugins and features directly to the eclipse folders.    As for the eclipse version, I pulled the “Eclipse IDE for Java Developers” version from the Eclipse Installation Details - Installed Software Tab  for id epp.package.java    and it is 1.5.2.20130211-18200.   Vrapper is showing up as 0.60.0.
The about eclipse window states that “eclipse IDE for Java Developers”  is Version: Juno Service Release 2, Build id: 20130225-0426.  I am running this in Oracle VM VirtualBox Manager.   By the way, after not being able to get vrapper working,  I was successfully able to load another Vi product ( viPlugin 2.14.0)  and it works and a VI icon for it does show on the toolbar. Any ideas?

**Comment by albertdev** [comment] 2015-11-03 09:21
Thank you for all that extra information. I happened to have  found a copy of Eclipse "Java EE IDE for Web Developers" which is also Build id: "20130225-0426".

However, installing Vrapper from the marketplace seemed to work fine when I restarted Eclipse after the installation.

It's possible that your Eclipse installation is now corrupted as moving files into the `eclipse/features` or `eclipse/plugins` folders is not recommended by Eclipse themself.

We could still try installing through the `eclipse/dropins` folder but I wonder if it isn't easier to start with a new Eclipse install. Would it be a lot of work for you to try in a newly unzipped Eclipse in some other location?

**Comment by finleyr** [comment] 2015-11-04 20:00
Is it possible that your eclipse installation is now corrupted from moving files into features and plugins?
Maybe … I do not know.
I did try the dropins method and that did not work either.

As I said, I am running everything in a Virtual box. In the middle of a build, but I will try during some leisure time to try a newly unzipped eclipse in another location and see what happens.

Thank you

**Comment by albertdev** [comment] 2016-04-02 16:37
@finleyr 
Did a fresh Eclipse and Vrapper install work?

**Comment by albertdev** [comment] 2016-04-02 22:19
Also, we just had a report that installing it on Windows can be best be done somewhere different than the `Program Files` directory, though I can't explain why `viPlugin` would work where `vrapper` wouldn't.

**Comment by keforbes** [comment] 2016-04-27 19:17
I'm closing this issue.  There's no point in leaving it open when we can't reproduce it and the person who reported it is not responding.  Nothing personal, I'm just trying to clean out some `Unconfirmed` issues.

**Closed by keforbes** 2016-04-27 19:17 UTC
Labels: Unconfirmed

**Comment by matteomartelli** [comment] 2017-04-12 08:04
I experienced the same issue on Eclipse Mars on Windows. After uninstalling vrapper, deleting all related files in eclipse/plugins and re-installing it, the icon did show up and vrapper is now working.
