### ISSUE TITLE
why  the cursor looks longer using vrapper

### ISSUE THREAD

**Issue by lvxingtu** [vrapper/vrapper#799] opened 2017-10-28 04:40 UTC
![image](https://user-images.githubusercontent.com/22794227/32131282-eed51202-bbdc-11e7-9766-9c7453503831.png)
![image](https://user-images.githubusercontent.com/22794227/32131283-0081752c-bbdd-11e7-9c9b-c7aae4a7e8ee.png)
![image](https://user-images.githubusercontent.com/22794227/32131289-09dc3cc4-bbdd-11e7-900e-9c0f1c171d2c.png)

**Comment by lvxingtu** [comment] 2017-10-28 06:56
it happend on linux system.
my windows system have not this problem

**Comment by keforbes** [comment] 2017-12-05 16:24
@lvxingtu, what version of Vrapper and Eclipse are you using?  @albertdev made a change to the cursor logic in one of our unstable builds to workaround an issue in Eclipse Neon, maybe that fix will be relevant here.  Although, if you're already using the unstable build maybe we messed something up. 😄 

To install the unstable build, add this site to your Ecilpse settings (Help -> Install New Software... -> Add):
http://vrapper.sourceforge.net/update-site/unstable
Then run Help -> Check for Updates and it should pick up the unstable build.

**Comment by keforbes** [comment] 2018-02-13 16:30
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:30 UTC
Labels: Unconfirmed
