### ISSUE TITLE
Toggle icon does nothing, Eclipse 3.7.2, no error log.

### ISSUE THREAD

**Issue by hukangha** [vrapper/vrapper#704] opened 2015-12-09 11:34 UTC
Hi, Engineers,
I'm using eclipse 3.7.2,
After installed Vrapper, the toggle icon appeared after restart.
but clicking it seems just nothing happens.
After searching for a while, I learned that there is an error log view may show something.
But it didn't.
I've no idea what to do, since no debug information is shown.

So, any suggestions?

**Comment by albertdev** [comment] 2015-12-09 11:48
Does your caret change in the current editor? When you have focussed the editor, can you see "NORMAL" in the status bar at the bottom of Eclipse or does it keep reading "vrapper disabled"?

**Comment by hukangha** [comment] 2015-12-12 14:43
@albertdev 
Hi, thanks for replying.
The caret is not changed.
The UI did not change at all except the toggle icon.
The behavior of the editor is still the same.
The status bar have nothing related to vrapper.
Can a customized eclipse cause this? 
I'm using my company's version. It's basically eclipse with a lot of company plugin.

**Comment by keforbes** [comment] 2015-12-15 04:10
Eclipse 3.7 is from 2011.  I wonder if we accidentally broke something in older (< 4.x) versions.  Could you try installing an older version?  I feel bad saying that since I don't know how far back you'll need to go, but it's something you could try.  http://sourceforge.net/projects/vrapper/files/vrapper/

**Comment by albertdev** [comment] 2015-12-15 10:50
This suspiciously sounds like it's another IBM product like in issue #708...

@hukangha
Could you go to http://gist.github.com and create a "secret" gist with some info for me?
What I need you to do is to go to "Help" > "About Eclipse", then clicking the "Installation details" button. A new window will open, in which you need to go to the last tab. The text-pane will fill up after some time, this is when you can click the "Copy to Clipboard" button at the bottom and paste it as that new gist.

**Comment by albertdev** [comment] 2015-12-28 22:50
@hukangha 
Do you have any more info as requested in my previous comment?

**Comment by albertdev** [comment] 2016-01-05 08:44
@hukangha 
I've finally taken the time to reproduce issue 708 and it seems I could do it with any old Eclipse 3.7 install.

We have pushed a new build (0.63.20160104) to our unstable update site which includes this fix. Could you install it to check if your Vrapper install then works fine?

**Comment by albertdev** [comment] 2016-01-08 09:28
Seeing how it's about a month ago since we've last heard from you I'm going to mark this issue as Unconfirmed and the issue will likely be closed at the next release.

**Comment by albertdev** [comment] 2016-02-05 12:38
I'm going to close this issue as I never heard back, a potential fix has released in version 0.64.0.

If there's any more information you are welcome to give it and reopen this issue.

**Closed by albertdev** 2016-02-05 12:38 UTC
Labels: Unconfirmed
