### ISSUE TITLE
Almost all the Eclipse interface becomes unusable

### ISSUE THREAD

**Issue by tuxayo** [vrapper/vrapper#769] opened 2016-11-11 18:15 UTC
It happens regularly and I have to kill Eclipse every time.

Clicking on any tab of any part of the interface doesn't work.
Navigating in the menu works but clicking on an item doesn't seem to trigger any action.
Editing and saving the file still works.
Auto build isn't triggered.
Resizing the window doesn't make the content to be resized (despite being redrawn)
![capture d ecran_2016-11-11_19-07-56](https://cloud.githubusercontent.com/assets/2678215/20225180/47c326a6-a842-11e6-9def-1ba84cd277d0.png)

Ctrl-Shift-R to open a resource made the window disappear despite the process being still here.

It happened on two different machines.
Disabling Vrapper prevents this from happening.

Eclipse version: eclipse-jee package 4.6.1-1 on Arch Linux
Vrapper version: 0.70.0 from the marketplace

**Comment by tuxayo** [comment] 2016-11-11 22:21
Happened again and the workspace `.metadata/.log` shows no additional message when Eclipse UI "locked"

**Comment by albertdev** [comment] 2016-11-11 22:37
Ugh. Is there any operation which you noticed that makes it more common?

Can you relate it to something which changed in your environment? What I mean is if this started happening shortly after you upgraded Eclipse or Vrapper.

**Comment by tuxayo** [comment] 2016-11-12 00:01
> Is there any operation which you noticed that makes it more common?

> Can you relate it to something which changed in your environment?

No correlation found yet.

I downloaded eclipse JEE Linux 64 bit because on another machine where I don't have root access, I use this portable version of Eclipse and get no issues with Vrapper.

So I had to install Vrapper again in this version, but anyway the issue happened again.

**Comment by tuxayo** [comment] 2016-11-12 21:55
The symptoms look like https://sourceforge.net/p/vrapper/discussion/901740/thread/8c016813/

I can search text and click on one of the results to select the text without triggering the issue.
Extracting to local variable also works.

**Comment by albertdev** [comment] 2016-11-21 14:13
Have you gotten any further in identifying a scenario? Are all your environments running Arch?

**Comment by tuxayo** [comment] 2016-11-22 14:04
> Have you gotten any further in identifying a scenario?

It still happened a few times but no reproducible scenario found.

> Are all your environments running Arch?

Yes, all the three different machines.

**Comment by albertdev** [comment] 2017-10-11 15:11
@tuxayo Any updates on this? If you happened to use Eclipse Oxygen, did it give any new info in the log or UI?

**Comment by tuxayo** [comment] 2017-10-22 12:15
I'll in the next few months use Eclipse for Perl development but not on Arch Linux. I'll see this issue still happens.

**Comment by keforbes** [comment] 2018-02-13 16:27
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:27 UTC
Labels: Unconfirmed
