### ISSUE TITLE
Eclipse 4.6 Neon: Issues with visual mode, highlighting, etc.

### ISSUE THREAD

**Issue by konradsa** [vrapper/vrapper#748] opened 2016-06-08 13:58 UTC
Looks like something changed in 0.68 that was not like this before. When pushing i for insert mode, the cursor remains a block, it doesn't change to the line that indicates insert mode even though the editor is actually in insert mode. Only after the first key is pressed (could be inserting a letter, or just moving the cursor), then the cursor switches to the line.

**Comment by konradsa** [comment] 2016-06-08 18:54
Btw, I tried downgrading to 0.66, but didn't fix the issue. This may be related to Neon RC3 I am using Vrapper in.

**Comment by konradsa** [comment] 2016-06-10 14:10
Btw, I just tried with the release version (available from the Eclipse Hudson page), and this is still broken.

**Comment by albertdev** [comment] 2016-06-10 21:31
I think I know what your first comment is all about: you have put `map i\ ...` in your `.vrapperrc` which means that Vrapper will wait for another character so that you either complete or fail that mapping.

You may want to replace those mappings with the `:subwordmappings` command to get the correct defaults, or replace it with `onoremap i\ <Plug>(subword-inner)` and `vnoremap i\ <Plug>(subword-inner)` so that your normal mode flow isn't bothered by it.

I think I'll have to check with @keforbes to change the documentation and homepage.

**Comment by albertdev** [comment] 2016-06-10 21:32
As for "highlighting" with the mouse (I prefer to call it "selecting"): you put `set novisualmouse` in your `.vrapperrc` which disables syncing the selection with Vrapper's visual mode. Is there any reason you put it there?

**Comment by konradsa** [comment] 2016-06-13 13:23
@albertdev Not sure why I did that, that may have just been a carryover from an old Vi configuration that I had when I switched to vrapper. Or maybe copy/paste didn't behave as I expected in some older version, since I am using a hybrid of Eclipse and Vi commands (e.g., using Crl-C/P for copy and paste).

Never had an issue before though, so something definitely changed that made it behave weirdly. But I disabled the following options now in my vrapperrc and now it seems fine. Let me see if that works as expected for me.

#set noati
#set novisualmouse

**Comment by keforbes** [comment] 2016-06-13 14:16
@albertdev, that's a good idea about the `i\` mapping.  We should change the `:subwordmappings` command so it doesn't interfere with normal mode.

**Comment by albertdev** [comment] 2016-06-14 09:51
@keforbes I think the `:subwordmappings` command already does the right thing; the mappings `a<Leader>` and `i<Leader>` are only registered in visual mode and operator modes. It's likely the documentation that needs fixing.

**Comment by keforbes** [comment] 2016-06-14 14:24
Gotcha.  I've updated the documentation to be more accurate but I haven't pushed it to the live website yet.  I also confirmed that if I use `:subwordmappings` I don't see the issue with `i` not changing the cursor style since I was seeing the same thing.

**Comment by keforbes** [comment] 2016-06-14 14:29
I'm going to close this issue since I think it was just some confusion with settings in `.vrapperrc`.  I believe everything is behaving as expected.

Also, the issue with `i` not changing the cursor until you hit another key is basically due to #741.  We currently wait indefinitely for the user to complete a mapping so the `i\` mapping wouldn't abort until you hit another key.

**Closed** 2016-06-14 14:31 UTC

**Comment by albertdev** [comment] 2016-06-15 08:13
Ah, now I see why `novisualmouse` no longer works: if you drag from the right to the left you will select near a line ending, thus triggering the same bug as #749.

**Comment by albertdev** [comment] 2016-06-18 19:02
@keforbes pushed a new build to our unstable site with a fix for the selection problem. If you want to revert your Vrapper install to the old selection behavior then you can install that version and put `set novisualmouse` back in your `.vrapperrc`.

**Comment by konradsa** [comment] 2016-06-20 13:38
I can confirm that novisulamouse seems to work correctly again now with the
unstable version. Thanks for the quick fix!
