### ISSUE TITLE
The continuous content assist operation causes the state to change from the INSERT mode to the NORMAL mode

### ISSUE THREAD

**Issue by Popo-lth** [vrapper/vrapper#790] opened 2017-08-26 13:30 UTC
OS: Ubuntu 16.04.2 LTS
eclipse:  Oxygen Release (4.7.0)
vrapper: 0.72.0

In INSERT mode, the state changes to NORMAL mode when I enter 'sys' and use 'alt + /' for content assist to select 'sysout' and press 'alt' again.

```java
    // The first step, in INSERT, enter 'sys' and 'alt+/'
    // The second step, enter 'alt', state becomes NORMAL
    System.out.println();
```

**Comment by albertdev** [comment] 2017-08-28 13:42
Do you have <kbd>Alt</kbd>+<kbd>/</kbd> assigned to "Content assist"? My workspace has that alt-combo assigned to "Word Completion", which will never give a dialog to pick a proposal.

I can't reproduce your problem though (using Vrapper 0.73.20170801). What values do you see in the status bar if you do `:set exitlinkmode?` or `:set contentassistmode?` from a Vrapper session?

**Comment by albertdev** [comment] 2017-09-16 14:23
@Popo-lth Any news or some more information on what functionality you are talking about?

**Comment by Popo-lth** [comment] 2017-09-18 01:45
exitlinkmode(On) and contentassistmode(Off) are the default values.

vrapper upgrade to 0.73.20170801  problems can be reproduced(Oxygen Release 4.7.0).

![](https://raw.githubusercontent.com/Popo-lth/Blog/master/img/vrapper/issues-790.gif)

**Comment by albertdev** [comment] 2017-10-15 21:51
@Popo-lth Thanks for that GIF.

It seems I cannot exactly reproduce what you are showing here (admittedly I'm testing on Windows). Once you have picked "sysout" from the command completion, you will notice that whaver you type next is inside a rectangle. This shows that you are in a (standard) Eclipse "parameter" mode where you can press <kbd>Tab</kbd> to switch to other rectangles, press <kbd>Enter</kbd>to complete the current statement or press <kbd>Esc</kbd> to leave everything alone. Exiting the Eclipse parameter mode is likely where your complain comes from because Vrapper will detect that mode switch and in turn go to Normal mode.

 Try putting `set noexitlinkmode` in your `.vrapperrc` or try finding out why your Eclipse will so easily exit its parameter editing mode. So far my Windows install remains in Eclipse parameter mode even when I run the second autocomplete to complete `String` after typing `str`.

**Comment by keforbes** [comment] 2018-02-13 16:28
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:28 UTC
Labels: Unconfirmed
