### ISSUE TITLE
autoindent doesn't appear to work

### ISSUE THREAD

**Issue by ScottChapman** [vrapper/vrapper#792] opened 2017-09-16 21:08 UTC
I've tried setting auto ident with no luck.

**Comment by albertdev** [comment] 2017-09-18 21:51
Hi there!

What were you trying to do? The reason I'm asking is that Vrapper's dirty little secret is that most of its formatting settings will not have any effect unless it you are using a Vrapper-exclusive functionality. Try e.g. `gqq` vs `==` - the former will is implemented purely in Vrapper whereas the latter simply uses the formatting tools from your JDT / CDT / PyDev editor.

In general it is best to find out how your current editor plugin works (JDT / CDT / PyDev / ...) and configure its formatting. Vrapper will then try its best to match that formatting unless you explicitly changed `expandtab`, `shiftwidth` or `tabstop`.

**Comment by ScottChapman** [comment] 2017-09-18 23:02
Trying :set autoindent

Behavior is a little odd, sometimes lines are indented sometimes not. Doesn't behave like vi(1)

**Comment by albertdev** [comment] 2017-10-15 21:57
@ScottChapman Again, Vrapper does not concern itself too much with formatting, instead it will delegate nearly everything to Eclipse.

Have you checked the Eclipse Preferences for formatting settings of the kind of file you are working with?

**Comment by keforbes** [comment] 2018-02-13 16:28
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:28 UTC
Labels: Unconfirmed
