### ISSUE TITLE
Cannot install on Mojave

### ISSUE THREAD

**Issue by Albert65** [vrapper/vrapper#824] opened 2019-03-12 16:22 UTC
Dear All, I just installed the latest Eclipse 2018-12 on Mojave Mac OS. There is no Vrapper in the standalone market place window (Help -> Eclipse Market place). However, if I open Market place site inside Eclipse, the Vrapper does present but is not installable.

**Comment by albertdev** [comment] 2019-03-15 11:10
Thank you for filing an issue, but I'm afraid we might not be able to help you with just the information you gave us. I do not have any Apple hardware (and thus no Mac OS X) and as far as I'm aware @keforbes doesn't either.

Have you tried opening the [Vrapper website](http://vrapper.sourceforge.net/home/) in a browser (outside of Eclipse) and then drag-and-dropping the "Install" button at the top right to your Eclipse window?

If that also doesn't work, could you try manually adding the update sites seen on the top-right of our website to your Eclipse install?

**Comment by Gael-Mifsud** [comment] 2019-03-15 11:28
Hello,
I think the problem is general and not only on MacOS because I am on Linux ubuntu 18.04 and I am experiencing the same problem : no vrapper in the MarketPlace.

And when I drag and drop the install button from vrapper eclipse page to my Eclipse window, it opens the marketplace but there is no vrapper to install in the list.

I have seen that in the Vrapper eclipse page (https://marketplace.eclipse.org/content/vrapper-vim) the Eclipse version supported stops to Eclipse 4.9 but **not Eclipse 4.10**. Perhaps is it why ?

**Comment by albertdev** [comment] 2019-03-15 13:54
Ah, I believe @keforbes never gave me access to the config page of the marketplace so I can't really check if there's a setting for that somewhere.

I'll try a fresh install then on my home machine somewhere during the weekend.

**Comment by keforbes** [comment] 2019-03-15 14:49
I didn't think the "Eclipse versions" area in the marketplace actually prevented installing the plugin, especially now that they're doing a release every couple months.  But, since I can't prove they _aren't_ I went ahead and changed it so Vrapper supports 4.10 (and 4.11 because why not).  Give it a try now and see if that helps.  If it works, I guess I'll have to update that page every time Eclipse has a new release.

**Comment by Gael-Mifsud** [comment] 2019-03-15 15:03
Thank you.
I can confirm that now, vrapper 0.74 is listed in the MarketPlace on Eclipse 4.10 PDT, on Ubuntu 18.04 (I don't know about Mojave, sorry to have hijacked your thread, Albert65), and I can install it.

It seems to be functional (I don't use all it's functionalities), but, on the eclipse error.log, I see :
**No .vrapperrc or _vrapperrc found.**
I don't know if it's relevant or important.

**Comment by keforbes** [comment] 2019-03-15 15:26
> on the eclipse error.log, I see :
> No .vrapperrc or _vrapperrc found.
> I don't know if it's relevant or important.

That's just our version of the `.vimrc` file for your custom settings.  All that error means is we didn't find any custom settings of yours, which I assume means you simply don't have any.  Not a problem at all.

**Comment by keforbes** [comment] 2019-03-20 19:00
@Albert65, is this problem resolved for you as well?  Can you try again?  I'm tempted to close this issue since it seems to be fixed.

**Comment by Albert65** [comment] 2019-03-27 17:36
Hi @keforbes, the issue has gone, at least on my system. Thank you very much.

**Closed** 2019-03-27 19:20 UTC
