### ISSUE TITLE
vrapper seems to break folding

### ISSUE THREAD

**Issue by elaforge** [vrapper/vrapper#738] opened 2016-04-19 23:28 UTC
Frequently I can't open folds.  Sometimes when I click the plus, I get this error.  But most of the time there's no error, it just doesn't open.  Since vrapper is in the traceback it seems to be implicated.

Eclipse version: Mars.2 (4.5.2)
Vrapper is 0.66.0.

```
  org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
    at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
    at org.eclipse.core.runtime.Assert.isTrue(Assert.java:96)
    at org.eclipse.jface.text.Position.<init>(Position.java:62)
    at org.eclipse.jface.text.Position.<init>(Position.java:52)
    at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.setMark(EclipseCursorAndSelection.java:657)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.rememberLastActiveSelection(DefaultEditorAdaptor.java:826)
    at net.sourceforge.vrapper.eclipse.interceptor.SelectionVisualHandler.selectionChanged(SelectionVisualHandler.java:96)
    at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
    at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:160)
    at org.eclipse.jface.text.TextViewer.fireSelectionChanged(TextViewer.java:2734)
    at org.eclipse.jface.text.TextViewer.selectionChanged(TextViewer.java:2713)
    at org.eclipse.jface.text.TextViewer$4.widgetSelected(TextViewer.java:1832)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1353)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1338)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1119)
    at org.eclipse.swt.custom.StyledText.sendSelectionEvent(StyledText.java:8200)
    at org.eclipse.swt.custom.StyledText.doSelection(StyledText.java:3255)
    at org.eclipse.swt.custom.StyledText.doMouseSelection(StyledText.java:2870)
    at org.eclipse.swt.custom.StyledText.doMouseLocationChange(StyledText.java:2853)
    at org.eclipse.swt.custom.StyledText.handleMouseMove(StyledText.java:6110)
    at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5690)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127) 
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)  
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by elaforge** [comment] 2016-04-19 23:30
Oh, and eclipse version: Mars.2 (4.5.2)
Vrapper is 0.66.0.

**Comment by albertdev** [comment] 2016-04-21 16:14
It appears the stacktrace happened when you were dragging a selection, likely close to a fold. Sadly I cannot reproduce it yes.

What kind of file are you editing? How many lines does the file have, and how many are folded?

**Comment by elaforge** [comment] 2016-04-21 23:44
I've gotten the error when I am viewing a .class file, so the source is not editable, but there is source attached to it, so I can see the source.  Unfortunately it's hard to reproduce.  I was hoping something would be obvious from the traceback alone.  The thing where folds won't expand happens all the time, but only rarely do I get the exception.  Mostly I just click on the + and nothing happens.

**Comment by keforbes** [comment] 2016-04-28 15:25
For this stack trace at least, it looks like you were selecting text with your mouse
```
at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.rememberLastActiveSelection(DefaultEditorAdaptor.java:826)
...
at org.eclipse.swt.custom.StyledText.sendSelectionEvent(StyledText.java:8200)
at org.eclipse.swt.custom.StyledText.doSelection(StyledText.java:3255)
at org.eclipse.swt.custom.StyledText.doMouseSelection(StyledText.java:2870)
at org.eclipse.swt.custom.StyledText.doMouseLocationChange(StyledText.java:2853)
at org.eclipse.swt.custom.StyledText.handleMouseMove(StyledText.java:6110)
```
Is it possible selecting text in a non-editable file is hitting some issue?  I couldn't reproduce this with a non-editable source file but maybe viewing class files is different?  What viewer are you using to view the .class file?  Do you have some special plugin for that?

**Comment by elaforge** [comment] 2016-06-03 23:25
There are some company-specific plugins here that might be muddying the waters, but this occurs while selecting text in an editable .java file.

I seem to get more errors than usual when working with cloned editors.  I think eclipse in general is buggy around there, so it might be unrelated.

**Comment by keforbes** [comment] 2018-02-13 16:27
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:27 UTC
Labels: Unconfirmed
