### ISSUE TITLE
Search and replace range skips current line when it should be included

### ISSUE THREAD

**Issue by OlivierLi** [vrapper/vrapper#609] opened 2015-03-10 14:04 UTC
For example with the lines : 

    foo_bar
    foo_bar
    foo_bar

The command `:.,+2s/bar/baz` if executed on the first line should result in  : 

    foo_baz
    foo_baz
    foo_baz

What is actually obtained : 

    foo_bar
    foo_baz
    foo_baz

**Comment by albertdev** [comment] 2015-03-10 14:59
I can't immediately reproduce this using 0.53.20150214 (an unstable version from february).

What kind of file are you editing in, what platform do you use and what version of Vrapper do you have installed?

**Comment by keforbes** [comment] 2015-03-11 03:26
I can't reproduce this with the latest unstable build either.  Seems to work fine for me.  Can you provide us with any more details?

**Comment by albertdev** [comment] 2015-05-05 12:40
@OlivierLi 
Vrapper 0.54.0 has been released in the mean time. Can you still reproduce it with that version?

**Comment by albertdev** [comment] 2015-11-10 08:52
Version 0.60.0 also had a lot of changes in all ex commands so it might just be fixed. I'm going to close this issue since we haven't heard back about problems.

Feel free to reopen this issue in case it comes back!

**Closed by albertdev** 2015-11-10 08:52 UTC
Labels: Unconfirmed
