### ISSUE TITLE
Mappings fail when one tries to use them after a character that begins a multi-character macro

### ISSUE THREAD

**Issue by McBrainy** [vrapper/vrapper#677] opened 2015-08-01 02:14 UTC
I have this in my `.vrapperrc`:

```vim
inoremap jk <Esc>
inoremap kj <Esc>
```

Let's say I have a variable named `luck`. I type the name of this variable, followed by `kj` to exit insert mode. In Vim, this works. In either Vim or Vrapper, when I type `luck`, it recognizes that the `k` begins a mapping and waits to see if I'll type a `j` after it. (In Vim, there's a timeout for this, and I wish Vrapper had the same.) When I type a `k` next, both editors recognize that I'm not typing `kj`, but only Vim is smart enough to say, "but wait, that second `k` might be the beginning of a mapping." So, in vim, I end up with `luck` and I'm normal mode, whereas Vrapper gives me `luckkj` and leaves me in insert mode.

In order for this to fully work, it would also have to be fixed for n-character mappings, I suppose. That is, if I had `abc` and `de` mapped and I typed `abde` or `ade`, it would have to recognize the second macro in either case.

**Comment by albertdev** [comment] 2015-08-01 13:22
Is it possible that this is related to or a duplicate of issue #669?

**Comment by McBrainy** [comment] 2015-08-01 16:12
Yes, that does sound the same, although I guess mine is more broad in its wording and thus, arguably, more useful.

**Comment by albertdev** [comment] 2015-11-15 18:07
I implemented general backtracking in the remapping logic. Command line mode and insert mode should now properly retry any mappings which they didn't pick up the first time.

This fix will be included in the next unstable and release build.

**Comment by keforbes** [comment] 2015-11-16 03:00
I've updated the unstable update site with a new build (0.61.20151115) which includes this fix. Please give it a try and let us know if you're still seeing any issues. Thanks!

**Closed** 2015-11-16 09:24 UTC
Labels: Defect
