### ISSUE TITLE
The Content Assist popup seemingly randomly pops up when auto activation is enabled with certain options

### ISSUE THREAD

**Issue by MrPay** [vrapper/vrapper#488] opened 2014-08-19 14:30 UTC
In preferences, i have <code>Java->Editor->Content Assist</code>, "Enable auto activation" enabled, with activation delay set to 0 ms and triggers set to all capital letters, lowercase letters, and various other characters like period.

The Content Assist popup will seemingly randomly popup while navigating a source file, when I'm not even in INSERT mode. I happen to find at least one reproducible moment when this happens, though:

Place the cursor on an instance variable and call a function that doesn't exist (<code>variable.newFunction();</code>) and make sure you are not in INSERT mode. Then use the <i>Quick Fix</i> <code>Ctrl-1</code> action and select "Create method 'newFunction". The word "newFunction" should then be selected while the function is created elsewhere. Now press the "h" key. The cursor should be placed after the "." on that line. And the Content Assist will now pop up with many suggestions, even though you're not even in insert mode. If you had been in insert mode before the quick fix, this is where you'd rename the identifier inline.

Other times I've seen the popup show up though, so far hasn't involved inline renaming though.

**Comment by keforbes** [comment] 2018-02-13 16:25
I'm going through all our Unconfirmed defects and closing them.  We're never going to fix these defects we couldn't reproduce.

**Closed by keforbes** 2018-02-13 16:25 UTC
Labels: Unconfirmed
