### ISSUE TITLE
Relative Number (feature request)

### ISSUE THREAD

**Issue by gbigwood** [vrapper/vrapper#697] opened 2015-11-02 17:23 UTC
I would love the ViM relative number feature. 

The ability to see the difference relative to the current line in the number on the left of the code would be fantastically useful.

**Comment by loonies** [comment] 2015-11-02 17:32
Duplicate of #630, #457.

**Comment by albertdev** [comment] 2015-11-04 08:42
@gbigwood 
Have you tried installing https://github.com/matf/relativenumberruler ?

It was actually designed to work together with Vrapper.

**Closed** 2015-11-23 18:36 UTC
